### ISSUE TITLE
Automatically include?

### ISSUE THREAD

**Issue by jandudulski** [monterail/rails_sso#21]
Right now we have this:

``` ruby
# lib/rails_sso/engine.rb#L3
initializer 'sso.helpers' do
  ActiveSupport.on_load(:action_controller) do
    include RailsSso::Helpers
  end
end
```

which automatically includes helpers into `ActionController::Base`. My question is - should we do this, or should we rely on explicit `include` in project controllers?

**Comment by teamon** [comment]
I think we should explicitly include it.
